# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af49d57314fca8488f50a5063c39943e5c86f6ce9a9f9c54d4cac563a0d2d637ae6ecc4d413393367216440ebaffc7238a1347146dc56f7c1470edfab4ad326

test:
  secret_key_base: 86e3e954f9c399f2ba54fde2336a77d6c52f33d16c9edf049a155a5a844e46f700eecfd459a1a1d0210392e9076f7e9afdfe729fae71c4ae59f5af16fbc56ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
